### ISSUE TITLE
Additional references

### ISSUE THREAD

**Issue by Zymrael** [2prime/ODE-DL#4]
Hey thanks for suggesting references in my other repo. Here are some for yours.

System Identification with Time-Aware Neural Sequence Models AAAI20
Dynamical System Inspired Adaptive Time Stepping Controller for Residual Network Families AAAI20
Graph Neural Ordinary Differential Equations arXiv19
Port-Hamiltonian Approach to Neural Network Training CDC19

**Comment by 2prime** [comment]
Sorry for late reply, I'm extremly busy these days and now I have added the reference
